on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/build-and-check.yaml

name: Build Artifacts and Deploy

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get install -y 'lld-10'

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: rusty-musicbot
          path: target/release/rusty-musicbot

  deploy:
    name: Deploy Artifacts
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: rusty-musicbot

      - name: Upload Files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: rusty-musicbot
          target: ${{ secrets.TARGET_PATH }}

      - name: Run Release
        uses: appleboy/ssh-action@v0.1.4
        env:
          PASS: ${{ secrets.PASSWORD }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: PASS,TARGET_PATH
          script: |
            chmod u+x $TARGET_PATH/rusty-musicbot
            echo $PASS | sudo -S systemctl restart rusty-musicbot

  checks:
    name: Check source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
